version: '3'
services:
  flask:
    build:
      context: "./app"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./app/src:/src
    tty: true
    ports:
      - 5901:5901