version: '3'
services:
  web:
    build:
      context: "./web"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./web/src:/src
    tty: true
    ports:
      - 5901:5901
    command: gunicorn -w 4 -b 0.0.0.0:5901 app:app
  user:
    build:
      context: "./user"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./user/src:/src
    depends_on:
      - web
    tty: true