version: '3'
services:
  web:
    build:
      context: "./web"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./web/src:/src
    tty: true
    expose:
      - 5901
    command: gunicorn -w 4 -b 0.0.0.0:5901 app:app
  nginx:
    build: ./nginx
    ports:
      - 8083:8083
    depends_on:
      - web
    networks:
      - nginx_network
  user:
    build:
      context: "./user"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./user/src:/src
    tty: true
    # command: locust -f locustfile.py --headless -u 100 -r 10 --run-time 10s
networks:
    flask-network:
        external: true