version: '3'
services:
  web:
    build:
      context: "./web"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./web/src:/src
    tty: true
    ports:
      - 5901:5901
    command: flask run --host=0.0.0.0 --port=5901
  user:
    build:
      context: "./user"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./user/src:/src
    depends_on:
      - web
    tty: true
    command: /home/user/.local/bin/locust -f locustfile.py --headless -u 1000 -r 100 --run-time 10s --csv=output