version: '3'
services:
  flask:
    build:
      context: "./app"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./app/src:/src
    tty: true
    ports:
      - 5901:5901
    # command: gunicorn -w 4 -b 0.0.0.0:5901 app:app
    command: flask run --host=0.0.0.0 --port=5901
  user:
    build:
      context: "./user"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    volumes:
      - ./user/src:/src
    tty: true
    # command: locust -f locustfile.py --headless -u 100 -r 10 --run-time 10s
networks:
    flask-network:
        external: true